# Generated by Django 5.2.6 on 2025-10-23 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(help_text='RUT del visitante (ej: 12345678-9)', max_length=12, unique=True, verbose_name='RUT')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre completo')),
                ('motivo_visita', models.TextField(max_length=500, verbose_name='Motivo de la visita')),
                ('fecha_visita', models.DateField(verbose_name='Fecha de visita')),
                ('hora_entrada', models.TimeField(verbose_name='Hora de entrada')),
                ('hora_salida', models.TimeField(blank=True, null=True, verbose_name='Hora de salida')),
                ('estado', models.CharField(choices=[('EN_CURSO', 'En curso'), ('FINALIZADA', 'Finalizada')], default='EN_CURSO', max_length=20, verbose_name='Estado de la visita')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('usuario_registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
                'ordering': ['-fecha_visita', '-hora_entrada'],
                'indexes': [models.Index(fields=['rut'], name='SistemaRegi_rut_5cb497_idx'), models.Index(fields=['fecha_visita'], name='SistemaRegi_fecha_v_45a089_idx'), models.Index(fields=['estado'], name='SistemaRegi_estado_6ab416_idx')],
            },
        ),
    ]
