# Generated by Django 5.2.6 on 2025-10-23 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaRegistros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='visita',
            name='SistemaRegi_rut_5cb497_idx',
        ),
        migrations.RemoveIndex(
            model_name='visita',
            name='SistemaRegi_fecha_v_45a089_idx',
        ),
        migrations.RemoveIndex(
            model_name='visita',
            name='SistemaRegi_estado_6ab416_idx',
        ),
        migrations.AlterField(
            model_name='visita',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='rut',
            field=models.CharField(max_length=12, verbose_name='RUT'),
        ),
    ]
